import { ShowdownInterpreter } from '../showdownInterpreter.js';
import { TurnHandler } from './TurnHandler.js';
import { SwitchHandler } from './SwitchHandler.js';
import { DamageHandler } from './DamageHandler.js';
import { HealHandler } from './HealHandler.js';
import { SetHpHandler } from './SetHpHandler.js';
import { StatusHandler } from './StatusHandler.js';
import { CureStatusHandler } from './CureStatusHandler.js';
import { StartHandler } from './StartHandler.js';
import { EndHandler } from './EndHandler.js';
import { FaintHandler } from './FaintHandler.js';
import { MoveHandler } from './MoveHandler.js';
import { WinHandler } from './WinHandler.js';
import { TieHandler } from './TieHandler.js';
import { CantHandler } from './CantHandler.js';
import { SupereffectiveHandler } from './SupereffectiveHandler.js';
import { ResistedHandler } from './ResistedHandler.js';
import { ImmuneHandler } from './ImmuneHandler.js';
import { MissHandler } from './MissHandler.js';
import { CritHandler } from './CritHandler.js';
import { BoostHandler } from './BoostHandler.js';
import { UnboostHandler } from './UnboostHandler.js';
import { WeatherHandler } from './WeatherHandler.js';
import { ItemHandler } from './ItemHandler.js';
import { AbilityHandler } from './AbilityHandler.js';
import { DetailsChangeHandler } from './DetailsChangeHandler.js';
import { FormeChangeHandler } from './FormeChangeHandler.js';
import { MegaHandler } from './MegaHandler.js';
import { PrimalHandler } from './PrimalHandler.js';

const switchHandler = new SwitchHandler();

ShowdownInterpreter.registerUpdate('turn', new TurnHandler());
ShowdownInterpreter.registerUpdate('switch', switchHandler);
ShowdownInterpreter.registerUpdate('drag', switchHandler);
ShowdownInterpreter.registerUpdate('-damage', new DamageHandler());
ShowdownInterpreter.registerUpdate('-heal', new HealHandler());
ShowdownInterpreter.registerUpdate('-sethp', new SetHpHandler());
ShowdownInterpreter.registerUpdate('-status', new StatusHandler());
ShowdownInterpreter.registerUpdate('-curestatus', new CureStatusHandler());
ShowdownInterpreter.registerUpdate('-start', new StartHandler());
ShowdownInterpreter.registerUpdate('-end', new EndHandler());
ShowdownInterpreter.registerUpdate('faint', new FaintHandler());
ShowdownInterpreter.registerUpdate('move', new MoveHandler());
ShowdownInterpreter.registerUpdate('win', new WinHandler());
ShowdownInterpreter.registerUpdate('tie', new TieHandler());
ShowdownInterpreter.registerUpdate('cant', new CantHandler());
ShowdownInterpreter.registerUpdate('-supereffective', new SupereffectiveHandler());
ShowdownInterpreter.registerUpdate('-resisted', new ResistedHandler());
ShowdownInterpreter.registerUpdate('-immune', new ImmuneHandler());
ShowdownInterpreter.registerUpdate('-miss', new MissHandler());
ShowdownInterpreter.registerUpdate('-crit', new CritHandler());
ShowdownInterpreter.registerUpdate('-boost', new BoostHandler());
ShowdownInterpreter.registerUpdate('-unboost', new UnboostHandler());
ShowdownInterpreter.registerUpdate('-weather', new WeatherHandler());
ShowdownInterpreter.registerUpdate('-item', new ItemHandler());
ShowdownInterpreter.registerUpdate('-ability', new AbilityHandler());
ShowdownInterpreter.registerUpdate('detailschange', new DetailsChangeHandler());
ShowdownInterpreter.registerUpdate('-formechange', new FormeChangeHandler());
ShowdownInterpreter.registerUpdate('-mega', new MegaHandler());
ShowdownInterpreter.registerUpdate('-primal', new PrimalHandler());
