export type CategoryName = keyof typeof backpackConfig;

interface BackpackConfig {
  [category: string]: {
    id: string;
    texturePath: string;
    displayName: string;
  }[];
}

export const CATEGORY_ICONS: Record<CategoryName, string> = {
  Pokeballs: "textures/ui/bag/pokeballs",
  Healing: "textures/ui/bag/healing",
  Berries: "textures/ui/bag/berries",
  MegaStones: "textures/ui/bag/megastones",
  BattleItems: "textures/ui/bag/battle_items",
  GenericItems: "textures/ui/bag/generic_items",
  HeldItems: "textures/ui/bag/kings_rock",
};

export const backpackConfig: BackpackConfig = {
  Pokeballs: [
    { displayName: "Beast Ball", id: "pokeworld:beastball", texturePath: "textures/items/ball/beastball" },
    { displayName: "Cherish Ball", id: "pokeworld:cherishball", texturePath: "textures/items/ball/cherishball" },
    { displayName: "Dive Ball", id: "pokeworld:diveball", texturePath: "textures/items/ball/diveball" },
    { displayName: "Dream Ball", id: "pokeworld:dreamball", texturePath: "textures/items/ball/dreamball" },
    { displayName: "Dusk Ball", id: "pokeworld:duskball", texturePath: "textures/items/ball/duskball" },
    { displayName: "Fast Ball", id: "pokeworld:fastball", texturePath: "textures/items/ball/fastball" },
    { displayName: "Friend Ball", id: "pokeworld:friendball", texturePath: "textures/items/ball/friendball" },
    { displayName: "Great Ball", id: "pokeworld:greatball", texturePath: "textures/items/ball/greatball" },
    { displayName: "Heal Ball", id: "pokeworld:healball", texturePath: "textures/items/ball/healball" },
    { displayName: "Heavy Ball", id: "pokeworld:heavyball", texturePath: "textures/items/ball/heavyball" },
    { displayName: "Level Ball", id: "pokeworld:levelball", texturePath: "textures/items/ball/levelball" },
    { displayName: "Love Ball", id: "pokeworld:loveball", texturePath: "textures/items/ball/loveball" },
    { displayName: "Luxury Ball", id: "pokeworld:luxuryball", texturePath: "textures/items/ball/luxuryball" },
    { displayName: "Lure Ball", id: "pokeworld:lureball", texturePath: "textures/items/ball/lureball" },
    { displayName: "Master Ball", id: "pokeworld:masterball", texturePath: "textures/items/ball/masterball" },
    { displayName: "Moon Ball", id: "pokeworld:moonball", texturePath: "textures/items/ball/moonball" },
    { displayName: "Nest Ball", id: "pokeworld:nestball", texturePath: "textures/items/ball/nestball" },
    { displayName: "Net Ball", id: "pokeworld:netball", texturePath: "textures/items/ball/netball" },
    { displayName: "Poke Ball", id: "pokeworld:pokeball", texturePath: "textures/items/ball/pokeball" },
    { displayName: "Premier Ball", id: "pokeworld:premierball", texturePath: "textures/items/ball/premierball" },
    { displayName: "Quick Ball", id: "pokeworld:quickball", texturePath: "textures/items/ball/quickball" },
    { displayName: "Repeat Ball", id: "pokeworld:repeatball", texturePath: "textures/items/ball/repeatball" },
    { displayName: "Safari Ball", id: "pokeworld:safariball", texturePath: "textures/items/ball/safariball" },
    { displayName: "Sport Ball", id: "pokeworld:sportball", texturePath: "textures/items/ball/sportball" },
    { displayName: "Timer Ball", id: "pokeworld:timerball", texturePath: "textures/items/ball/timerball" },
    { displayName: "Ultra Ball", id: "pokeworld:ultraball", texturePath: "textures/items/ball/ultraball" },
    { displayName: "Arkadia Ball", id: "pokeworld:arkadiaball", texturePath: "textures/items/ball/arkadiaball" }
  ],
  Healing: [
    { displayName: "Antidote", id: "pokeworld:antidote", texturePath: "textures/items/medicine/antidote" },
    { displayName: "Awakening", id: "pokeworld:awakening", texturePath: "textures/items/medicine/awakening" },
    { displayName: "Burn Heal", id: "pokeworld:burn_heal", texturePath: "textures/items/medicine/burn_heal" },
    { displayName: "Energy Powder", id: "pokeworld:energy_powder", texturePath: "textures/items/medicine/energy_powder" },
    { displayName: "Energy Root", id: "pokeworld:energy_root", texturePath: "textures/items/medicine/energy_root" },
    { displayName: "Elixir", id: "pokeworld:elixir", texturePath: "textures/items/medicine/elixir" },
    { displayName: "Ether", id: "pokeworld:ether", texturePath: "textures/items/medicine/ether" },
    { displayName: "Fresh Water", id: "pokeworld:fresh_water", texturePath: "textures/items/medicine/fresh_water" },
    { displayName: "Full Heal", id: "pokeworld:full_heal", texturePath: "textures/items/medicine/full_heal" },
    { displayName: "Full Restore", id: "pokeworld:full_restore", texturePath: "textures/items/medicine/full_restore" },
    { displayName: "Heal Powder", id: "pokeworld:heal_powder", texturePath: "textures/items/medicine/heal_powder" },
    { displayName: "Hyper Potion", id: "pokeworld:hyper_potion", texturePath: "textures/items/medicine/hyper_potion" },
    { displayName: "Ice Heal", id: "pokeworld:ice_heal", texturePath: "textures/items/medicine/ice_heal" },
    { displayName: "Lemonade", id: "pokeworld:lemonade", texturePath: "textures/items/medicine/lemonade" },
    { displayName: "Max Elixir", id: "pokeworld:max_elixir", texturePath: "textures/items/medicine/max_elixir" },
    { displayName: "Max Ether", id: "pokeworld:max_ether", texturePath: "textures/items/medicine/max_ether" },
    { displayName: "Max Potion", id: "pokeworld:max_potion", texturePath: "textures/items/medicine/max_potion" },
    { displayName: "Moo Moo Milk", id: "pokeworld:moomoo_milk", texturePath: "textures/items/medicine/moomoo_milk" },
    { displayName: "Paralyze Heal", id: "pokeworld:paralyze_heal", texturePath: "textures/items/medicine/paralyze_heal" },
    { displayName: "Potion", id: "pokeworld:potion", texturePath: "textures/items/medicine/potion" },
    { displayName: "Rage Candy Bar", id: "pokeworld:rage_candy_bar", texturePath: "textures/items/medicine/rage_candy_bar" },
    { displayName: "Sacred Ash", id: "pokeworld:sacred_ash", texturePath: "textures/items/medicine/sacred_ash" },
    { displayName: "Super Potion", id: "pokeworld:super_potion", texturePath: "textures/items/medicine/super_potion" },
    { displayName: "Max Revive", id: "pokeworld:max_revive", texturePath: "textures/items/medicine/max_revive" },
    { displayName: "Revive", id: "pokeworld:revive", texturePath: "textures/items/medicine/revive" },
  ],
  Berries: [
    // --- Status / Healing ---
    { displayName: "Cheri Berry", id: "pokeworld:cheri_berry", texturePath: "textures/items/berry/cheri" },
    { displayName: "Chesto Berry", id: "pokeworld:chesto_berry", texturePath: "textures/items/berry/chesto" },
    { displayName: "Pecha Berry", id: "pokeworld:pecha_berry", texturePath: "textures/items/berry/pecha" },
    { displayName: "Rawst Berry", id: "pokeworld:rawst_berry", texturePath: "textures/items/berry/rawst" },
    { displayName: "Aspear Berry", id: "pokeworld:aspear_berry", texturePath: "textures/items/berry/aspear" },
    { displayName: "Persim Berry", id: "pokeworld:persim_berry", texturePath: "textures/items/berry/persim" },
    { displayName: "Lum Berry", id: "pokeworld:lum_berry", texturePath: "textures/items/berry/lum" },

    // --- HP / PP ---
    { displayName: "Oran Berry", id: "pokeworld:oran_berry", texturePath: "textures/items/berry/oran" },
    { displayName: "Sitrus Berry", id: "pokeworld:sitrus_berry", texturePath: "textures/items/berry/sitrus" },
    { displayName: "Leppa Berry", id: "pokeworld:leppa_berry", texturePath: "textures/items/berry/leppa" },

    // --- EV Reducing ---
    { displayName: "Pomeg Berry", id: "pokeworld:pomeg_berry", texturePath: "textures/items/berry/pomeg" },
    { displayName: "Kelpsy Berry", id: "pokeworld:kelpsy_berry", texturePath: "textures/items/berry/kelpsy" },
    { displayName: "Qualot Berry", id: "pokeworld:qualot_berry", texturePath: "textures/items/berry/qualot" },
    { displayName: "Hondew Berry", id: "pokeworld:hondew_berry", texturePath: "textures/items/berry/hondew" },
    { displayName: "Grepa Berry", id: "pokeworld:grepa_berry", texturePath: "textures/items/berry/grepa" },
    { displayName: "Tamato Berry", id: "pokeworld:tamato_berry", texturePath: "textures/items/berry/tamato" },

    // --- Pinch Berries ---
    { displayName: "Figy Berry", id: "pokeworld:figy_berry", texturePath: "textures/items/berry/figy" },
    { displayName: "Wiki Berry", id: "pokeworld:wiki_berry", texturePath: "textures/items/berry/wiki" },
    { displayName: "Mago Berry", id: "pokeworld:mago_berry", texturePath: "textures/items/berry/mago" },
    { displayName: "Aguav Berry", id: "pokeworld:aguav_berry", texturePath: "textures/items/berry/aguav" },
    { displayName: "Iapapa Berry", id: "pokeworld:iapapa_berry", texturePath: "textures/items/berry/iapapa" },

    // --- Type-Resist ---
    { displayName: "Occa Berry", id: "pokeworld:occa_berry", texturePath: "textures/items/berry/occa" },
    { displayName: "Passho Berry", id: "pokeworld:passho_berry", texturePath: "textures/items/berry/passho" },
    { displayName: "Wacan Berry", id: "pokeworld:wacan_berry", texturePath: "textures/items/berry/wacan" },
    { displayName: "Rindo Berry", id: "pokeworld:rindo_berry", texturePath: "textures/items/berry/rindo" },
    { displayName: "Yache Berry", id: "pokeworld:yache_berry", texturePath: "textures/items/berry/yache" },
    { displayName: "Chople Berry", id: "pokeworld:chople_berry", texturePath: "textures/items/berry/chople" },
    { displayName: "Kebia Berry", id: "pokeworld:kebia_berry", texturePath: "textures/items/berry/kebia" },
    { displayName: "Shuca Berry", id: "pokeworld:shuca_berry", texturePath: "textures/items/berry/shuca" },
    { displayName: "Coba Berry", id: "pokeworld:coba_berry", texturePath: "textures/items/berry/coba" },
    { displayName: "Payapa Berry", id: "pokeworld:payapa_berry", texturePath: "textures/items/berry/payapa" },
    { displayName: "Tanga Berry", id: "pokeworld:tanga_berry", texturePath: "textures/items/berry/tanga" },
    { displayName: "Charti Berry", id: "pokeworld:charti_berry", texturePath: "textures/items/berry/charti" },
    { displayName: "Kasib Berry", id: "pokeworld:kasib_berry", texturePath: "textures/items/berry/kasib" },
    { displayName: "Haban Berry", id: "pokeworld:haban_berry", texturePath: "textures/items/berry/haban" },
    { displayName: "Colbur Berry", id: "pokeworld:colbur_berry", texturePath: "textures/items/berry/colbur" },
    { displayName: "Babiri Berry", id: "pokeworld:babiri_berry", texturePath: "textures/items/berry/babiri" },
    { displayName: "Chilan Berry", id: "pokeworld:chilan_berry", texturePath: "textures/items/berry/chilan" },

    // --- Stat / Rare ---
    { displayName: "Liechi Berry", id: "pokeworld:liechi_berry", texturePath: "textures/items/berry/liechi" },
    { displayName: "Ganlon Berry", id: "pokeworld:ganlon_berry", texturePath: "textures/items/berry/ganlon" },
    { displayName: "Salac Berry", id: "pokeworld:salac_berry", texturePath: "textures/items/berry/salac" },
    { displayName: "Petaya Berry", id: "pokeworld:petaya_berry", texturePath: "textures/items/berry/petaya" },
    { displayName: "Apicot Berry", id: "pokeworld:apicot_berry", texturePath: "textures/items/berry/apicot" },
    { displayName: "Lansat Berry", id: "pokeworld:lansat_berry", texturePath: "textures/items/berry/lansat" },
    { displayName: "Starf Berry", id: "pokeworld:starf_berry", texturePath: "textures/items/berry/starf" },
    { displayName: "Enigma Berry", id: "pokeworld:enigma_berry", texturePath: "textures/items/berry/enigma" },
    { displayName: "Micle Berry", id: "pokeworld:micle_berry", texturePath: "textures/items/berry/micle" },
    { displayName: "Custap Berry", id: "pokeworld:custap_berry", texturePath: "textures/items/berry/custap" },
    { displayName: "Jaboca Berry", id: "pokeworld:jaboca_berry", texturePath: "textures/items/berry/jaboca" },
    { displayName: "Rowap Berry", id: "pokeworld:rowap_berry", texturePath: "textures/items/berry/rowap" },

    // --- Gen 6+ ---
    { displayName: "Kee Berry", id: "pokeworld:kee_berry", texturePath: "textures/items/berry/kee" },
    { displayName: "Maranga Berry", id: "pokeworld:maranga_berry", texturePath: "textures/items/berry/maranga" },
    { displayName: "Roseli Berry", id: "pokeworld:roseli_berry", texturePath: "textures/items/berry/roseli" }
  ],

  MegaStones: [
    { displayName: "Venusaurite", id: "pokeworld:venusaurite", texturePath: "textures/items/mega_stone/venusaurite" },
    { displayName: "Charizardite X", id: "pokeworld:charizardite_x", texturePath: "textures/items/mega_stone/charizardite_x" },
    { displayName: "Charizardite Y", id: "pokeworld:charizardite_y", texturePath: "textures/items/mega_stone/charizardite_y" },
    { displayName: "Blastoisinite", id: "pokeworld:blastoisinite", texturePath: "textures/items/mega_stone/blastoisinite" },
    { displayName: "Alakazite", id: "pokeworld:alakazite", texturePath: "textures/items/mega_stone/alakazite" },
    { displayName: "Gengarite", id: "pokeworld:gengarite", texturePath: "textures/items/mega_stone/gengarite" },
    { displayName: "Kangaskhanite", id: "pokeworld:kangaskhanite", texturePath: "textures/items/mega_stone/kangaskhanite" },
    { displayName: "Pinsirite", id: "pokeworld:pinsirite", texturePath: "textures/items/mega_stone/pinsirite" },
    { displayName: "Gyaradosite", id: "pokeworld:gyaradosite", texturePath: "textures/items/mega_stone/gyaradosite" },
    { displayName: "Aerodactylite", id: "pokeworld:aerodactylite", texturePath: "textures/items/mega_stone/aerodactylite" },
    { displayName: "Abomasite", id: "pokeworld:abomasite", texturePath: "textures/items/mega_stone/abomasite" },
    { displayName: "Absolite", id: "pokeworld:absolite", texturePath: "textures/items/mega_stone/absolite" },
    { displayName: "Aerodactylite", id: "pokeworld:aerodactylite", texturePath: "textures/items/mega_stone/aerodactylite" },
    { displayName: "Aggronite", id: "pokeworld:aggronite", texturePath: "textures/items/mega_stone/aggronite" },
    { displayName: "Alakazite", id: "pokeworld:alakazite", texturePath: "textures/items/mega_stone/alakazite" },
    { displayName: "Altarianite", id: "pokeworld:altarianite", texturePath: "textures/items/mega_stone/altarianite" },
    { displayName: "Ampharosite", id: "pokeworld:ampharosite", texturePath: "textures/items/mega_stone/ampharosite" },
    { displayName: "Audinite", id: "pokeworld:audinite", texturePath: "textures/items/mega_stone/audinite" },
    { displayName: "Banettite", id: "pokeworld:banettite", texturePath: "textures/items/mega_stone/banettite" },
    { displayName: "Beedrillite", id: "pokeworld:beedrillite", texturePath: "textures/items/mega_stone/beedrillite" },
    { displayName: "Blastoisinite", id: "pokeworld:blastoisinite", texturePath: "textures/items/mega_stone/blastoisinite" },
    { displayName: "Blazikenite", id: "pokeworld:blazikenite", texturePath: "textures/items/mega_stone/blazikenite" },
    { displayName: "Cameruptite", id: "pokeworld:cameruptite", texturePath: "textures/items/mega_stone/cameruptite" },
    { displayName: "Garchompite", id: "pokeworld:garchompite", texturePath: "textures/items/mega_stone/garchompite" },
    { displayName: "Gardevoirite", id: "pokeworld:gardevoirite", texturePath: "textures/items/mega_stone/gardevoirite" },
    { displayName: "Gengarite", id: "pokeworld:gengarite", texturePath: "textures/items/mega_stone/gengarite" },
    { displayName: "Glalitite", id: "pokeworld:glalitite", texturePath: "textures/items/mega_stone/glalitite" },
    { displayName: "Heracronite", id: "pokeworld:heracronite", texturePath: "textures/items/mega_stone/heracronite" },
    { displayName: "Houndoominite", id: "pokeworld:houndoominite", texturePath: "textures/items/mega_stone/houndoominite" },
    { displayName: "Kangaskhanite", id: "pokeworld:kangaskhanite", texturePath: "textures/items/mega_stone/kangaskhanite" },
    { displayName: "Latiasite", id: "pokeworld:latiasite", texturePath: "textures/items/mega_stone/latiasite" },
    { displayName: "Latiosite", id: "pokeworld:latiosite", texturePath: "textures/items/mega_stone/latiosite" },
    { displayName: "Lopunnite", id: "pokeworld:lopunnite", texturePath: "textures/items/mega_stone/lopunnite" },
    { displayName: "Lucarionite", id: "pokeworld:lucarionite", texturePath: "textures/items/mega_stone/lucarionite" },
    { displayName: "Mawilite", id: "pokeworld:mawilite", texturePath: "textures/items/mega_stone/mawilite" },
    { displayName: "Medichamite", id: "pokeworld:medichamite", texturePath: "textures/items/mega_stone/medichamite" },
    { displayName: "Metagrossite", id: "pokeworld:metagrossite", texturePath: "textures/items/mega_stone/metagrossite" },
    { displayName: "Mewtwonite X", id: "pokeworld:mewtwonite_x", texturePath: "textures/items/mega_stone/mewtwonite_x" },
    { displayName: "Mewtwonite Y", id: "pokeworld:mewtwonite_y", texturePath: "textures/items/mega_stone/mewtwonite_y" },
    { displayName: "Milotite", id: "pokeworld:milotite", texturePath: "textures/items/mega_stone/milotite" },
    { displayName: "Miltankite", id: "pokeworld:miltankite", texturePath: "textures/items/mega_stone/miltankite" },
    { displayName: "Pidgeotite", id: "pokeworld:pidgeotite", texturePath: "textures/items/mega_stone/pidgeotite" },
    { displayName: "Pinsirite", id: "pokeworld:pinsirite", texturePath: "textures/items/mega_stone/pinsirite" },
    { displayName: "Politoedite", id: "pokeworld:politoedite", texturePath: "textures/items/mega_stone/politoedite" },
    { displayName: "Poliwrathite", id: "pokeworld:poliwrathite", texturePath: "textures/items/mega_stone/poliwrathite" },
    { displayName: "Reuniclite", id: "pokeworld:reuniclite", texturePath: "textures/items/mega_stone/reuniclite" },
    { displayName: "Sablenite", id: "pokeworld:sablenite", texturePath: "textures/items/mega_stone/sablenite" },
    { displayName: "Sceptilite", id: "pokeworld:sceptilite", texturePath: "textures/items/mega_stone/sceptilite" },
    { displayName: "Scizorite", id: "pokeworld:scizorite", texturePath: "textures/items/mega_stone/scizorite" },
    { displayName: "Sharpedonite", id: "pokeworld:sharpedonite", texturePath: "textures/items/mega_stone/sharpedonite" },
    { displayName: "Slowbronite", id: "pokeworld:slowbronite", texturePath: "textures/items/mega_stone/slowbronite" },
    { displayName: "Stunfiskite", id: "pokeworld:stunfiskite", texturePath: "textures/items/mega_stone/stunfiskite" },
    { displayName: "Swampertite", id: "pokeworld:swampertite", texturePath: "textures/items/mega_stone/swampertite" },
    { displayName: "Tyranitarite", id: "pokeworld:tyranitarite", texturePath: "textures/items/mega_stone/tyranitarite" }
  ],

  BattleItems: [
    { displayName: "X Attack", id: "pokeworld:x_attack", texturePath: "textures/items/battle_item/x_attack" },
    { displayName: "X Defense", id: "pokeworld:x_defense", texturePath: "textures/items/battle_item/x_defense" },
    { displayName: "X Speed", id: "pokeworld:x_speed", texturePath: "textures/items/battle_item/x_speed" },
    { displayName: "X Accuracy", id: "pokeworld:x_accuracy", texturePath: "textures/items/battle_item/x_accuracy" },
    { displayName: "X Sp. Atk", id: "pokeworld:x_spatk", texturePath: "textures/items/battle_item/x_spatk" },
    { displayName: "X Sp. Def", id: "pokeworld:x_spdef", texturePath: "textures/items/battle_item/x_spdef" },
    { displayName: "Dire Hit", id: "pokeworld:dire_hit", texturePath: "textures/items/battle_item/dire_hit" },
    { displayName: "Guard Spec", id: "pokeworld:guard_spec", texturePath: "textures/items/battle_item/guard_spec" },
    { displayName: "Ability Capsule", id: "pokeworld:ability_capsule", texturePath: "textures/items/battle_item/ability_capsule" }
  ],

  GenericItems: [
    { displayName: "Rare Candy", id: "pokeworld:rare_candy", texturePath: "textures/items/rare_candy" },
    { displayName: "Blue Shard", id: "pokeworld:blue_shard", texturePath: "textures/items/blue_shard" },
    { displayName: "Red Shard", id: "pokeworld:red_shard", texturePath: "textures/items/red_shard" },
    { displayName: "Yellow Shard", id: "pokeworld:yellow_shard", texturePath: "textures/items/yellow_shard" },
    { displayName: "Green Shard", id: "pokeworld:green_shard", texturePath: "textures/items/green_shard" },
    { displayName: "Rare Bone", id: "pokeworld:rare_bone", texturePath: "textures/items/rare_bone" },
    { displayName: "Heart Scale", id: "pokeworld:heart_scale", texturePath: "textures/items/heart_scale" },
    { displayName: "Shiny Charm", id: "pokeworld:shiny_charm", texturePath: "textures/items/shiny_charm" },
    { displayName: "Fire Stone", id: "pokeworld:fire_stone", texturePath: "textures/items/fire_stone" },
    { displayName: "Water Stone", id: "pokeworld:water_stone", texturePath: "textures/items/water_stone" },
    { displayName: "Thunder Stone", id: "pokeworld:thunder_stone", texturePath: "textures/items/thunder_stone" },
    { displayName: "Leaf Stone", id: "pokeworld:leaf_stone", texturePath: "textures/items/leaf_stone" },
    { displayName: "Moon Stone", id: "pokeworld:moon_stone", texturePath: "textures/items/moon_stone" },
    { displayName: "Sun Stone", id: "pokeworld:sun_stone", texturePath: "textures/items/sun_stone" },
    { displayName: "Shiny Stone", id: "pokeworld:shiny_stone", texturePath: "textures/items/shiny_stone" },
    { displayName: "Dusk Stone", id: "pokeworld:dusk_stone", texturePath: "textures/items/dusk_stone" },
    { displayName: "Dawn Stone", id: "pokeworld:dawn_stone", texturePath: "textures/items/dawn_stone" },
    { displayName: "Ice Stone", id: "pokeworld:ice_stone", texturePath: "textures/items/ice_stone" },
    { displayName: "Oval Stone", id: "pokeworld:oval_stone", texturePath: "textures/items/oval_stone" }
  ],
  HeldItems: [
    { displayName: "Metal Coat", id: "pokeworld:metal_coat", texturePath: "textures/items/metal_coat" },
    { displayName: "Dragon Scale", id: "pokeworld:dragon_scale", texturePath: "textures/items/dragon_scale" },
    { displayName: "Up-Grade", id: "pokeworld:up_grade", texturePath: "textures/items/up_grade" },
    { displayName: "Dubious Disc", id: "pokeworld:dubious_disc", texturePath: "textures/items/dubious_disc" },
    { displayName: "Protector", id: "pokeworld:protector", texturePath: "textures/items/protector" },
    { displayName: "Electirizer", id: "pokeworld:electirizer", texturePath: "textures/items/electirizer" },
    { displayName: "Magmarizer", id: "pokeworld:magmarizer", texturePath: "textures/items/magmarizer" },
    { displayName: "Prism Scale", id: "pokeworld:prism_scale", texturePath: "textures/items/prism_scale" },
    { displayName: "Reaper Cloth", id: "pokeworld:reaper_cloth", texturePath: "textures/items/reaper_cloth" },
    { displayName: "Razor Claw", id: "pokeworld:razor_claw", texturePath: "textures/items/razor_claw" },
    { displayName: "Razor Fang", id: "pokeworld:razor_fang", texturePath: "textures/items/razor_fang" },
    { displayName: "Deep Sea Scale", id: "pokeworld:deep_sea_scale", texturePath: "textures/items/deep_sea_scale" },
    { displayName: "Deep Sea Tooth", id: "pokeworld:deep_sea_tooth", texturePath: "textures/items/deep_sea_tooth" },
    { displayName: "Black Augurite", id: "pokeworld:black_augurite", texturePath: "textures/items/black_augurite" }
  ]
} as const;